---
# tasks file for app.wordpress
- block:
  - name: Make sure all of the WordPress nginx configs exist
    copy: src=nginx/conf.d/{{item}} dest=/etc/nginx/conf.d/global/{{item}}
    with_items:
      - wordpress.conf
    notify: restart nginx

  # Individual instance setup
  - name: Create vhost
    template: src=nginx/vhost.conf dest=/etc/nginx/sites-enabled/{{domain}}
    notify: restart nginx

  - name: Create location on disk
    file: path=/var/www/{{domain}}/www/html state=directory

  - name: Does the database exist?
    command: mysql -u root {{db_name}} -e "SELECT ID FROM {{db_name}}.wp_users LIMIT 1;"
    register: db_exist
    ignore_errors: true

  - name: Create the DB if it doesn't exist
    mysql_db: name={{db_name}} state=present
    when: db_exist.rc > 0

  - name: Create DB user
    mysql_user: name={{db_user}} host=localhost password={{db_password}} priv="{{db_name}}.*:ALL"
    when: db_exist.rc > 0

  - name: Copy backup on to remote machine
    copy: src={{db_backup}} dest=/tmp/{{db_name}}

  - name: Import the database
    mysql_db: target=/tmp/{{db_name}} state=import name={{db_name}}
    when: db_exist.rc > 0

    
  become: true
