- name: fontconfig | Install AUR fonts
  yaourt: name={{item}} state=present
  with_items:
    - fonts-meta-base
    - fonts-meta-extended-lt

- name: fontconfig | Copy package fonts
  copy: src="fonts/{{item}}" dest="/tmp/{{item}}"
  with_items:
    - t1-cursor-ib-1.0.4-2-any.pkg.tar.xz
    - ttf-gelasio-ib-1.00-7-any.pkg.tar.xz

- name: fontconfig | Install package fonts
  pacman: name="/tmp/{{item}}" state=present
  with_items:
    - t1-cursor-ib-1.0.4-2-any.pkg.tar.xz
    - ttf-gelasio-ib-1.00-7-any.pkg.tar.xz

- name: fontconfig | Create symlinks
  file: src={{item.src}} dest={{item.dest}} state=link
  with_items:
    - {"src":"/etc/fonts/conf.avail/11-lcdfilter-default.conf", "dest":"/etc/fonts/conf.d/11-lcdfilter-default.conf"}
    - {"src":"/etc/fonts/conf.avail/10-sub-pixel-rgb.conf", "dest":"/etc/fonts/conf.d/10-sub-pixel-rgb.conf"}
    - {"src":"/etc/fonts/conf.avail/10-hinting-slight.conf", "dest":"/etc/fonts/conf.d/10-hinting-slight.conf"}
    - {"src":"/etc/fonts/conf.avail/30-infinality-aliases.conf", "dest":"/etc/fonts/conf.d/30-infinality-aliases.conf"}
  become: true

