- name: lightdm | Install LightDM
  pacman: name={{item}} state=installed
  with_items:
    - lightdm
    - lightdm-gtk-greeter
  become: true

- name: lightdm | Enable LightDM
  systemd: name=lightdm enabled=true


