- name: xserver | Install X
  pacman: name={{item}} state=installed
  with_items:
    - xf86-input-evdev
    - nvidia
    - xorg-server
    - xorg-xrandr
    - xorg-xdpyinfo
    - xorg-xrdb
    - arandr
  become: true


