- name: Install development homebrew casks
  homebrew_cask: name="{{item}}" state=present
  with_items:
    - chefdk
    - iterm2
    - vagrant
    - virtualbox

- name: Install user homebrew casks
  homebrew_cask: name="{{item}}" state=present
  with_items:
    - 1password
    - alfred
    - beamer
    - calibre
    - dropbox
    #- fantastical
    - google-chrome
    #- screenflow # Disabled, version too new
    - slack
    - spotify
    - steam
    - utorrent
    - vlc
    - ynab
